// import Sidebar from "@/components/sidebarNavigation/sidebarNavigation";
import SidebarClientWrapper from "@/components/sidebarNavigation/SidebarClientWrapper";
import Providers from "@/redux/provider/providers";
import ThemeContextProvider from "@/src/theme/themeContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Curewell--admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeContextProvider>
        <Providers>
          <SidebarClientWrapper />
          {children}
          <Toaster position="top-right" richColors />
        </Providers>
        </ThemeContextProvider>
        
      </body>
    </html>
  );
}
